/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro.lab.pkg2.pkg3;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class AdminEkrani extends javax.swing.JFrame {
KullaniciIslemleri kullaniciIslemleri=new KullaniciIslemleri();
    SarkiIslemleri sarkiIslemleri = new SarkiIslemleri();
    DefaultTableModel sanatciModel;
    DefaultTableModel sarkiModel;
    DefaultTableModel albumModel;

    public AdminEkrani() {
        initComponents();
        sanatciModel = (DefaultTableModel) sanatciTablosu.getModel();
        sarkiModel = (DefaultTableModel) sarkiTablosu.getModel();
        albumModel = (DefaultTableModel) albumTablosu.getModel();
        sanatciTablosunuGoruntule();
        sarkiTablosunuGoruntule();
        albumTablosunuGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sanatciTablosu = new javax.swing.JTable();
        sanatciEkleButonu = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        sarkiGuncelle = new javax.swing.JButton();
        albumGuncelle = new javax.swing.JButton();
        sanatciGuncelleButonu = new javax.swing.JButton();
        sarkiSilButonu = new javax.swing.JButton();
        albumSilButonu = new javax.swing.JButton();
        sanatciSilButonu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        albumTablosu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        sarkiTablosu = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        sarkiAdiAlani = new javax.swing.JTextField();
        tarihAlani = new javax.swing.JTextField();
        sanatciAlani = new javax.swing.JTextField();
        turAlani = new javax.swing.JTextField();
        dinlenmeSayisiAlani = new javax.swing.JTextField();
        albumAlani = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        ulkeAlani = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        sureAlani = new javax.swing.JTextField();
        yenileButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(75, 25, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Albüm Ekle");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 290, 80, 30));

        sanatciTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sanatçı", "Ülke"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sanatciTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanatciTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sanatciTablosu);
        if (sanatciTablosu.getColumnModel().getColumnCount() > 0) {
            sanatciTablosu.getColumnModel().getColumn(0).setResizable(false);
            sanatciTablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 329, 183));

        sanatciEkleButonu.setText("Sanatçı Ekle");
        sanatciEkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciEkleButonuActionPerformed(evt);
            }
        });
        getContentPane().add(sanatciEkleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 100, 30));

        jButton5.setText("Şarkı Ekle");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 630, 100, 30));

        sarkiGuncelle.setText("Şarkı Güncelle");
        getContentPane().add(sarkiGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 110, 30));

        albumGuncelle.setText("Albüm Güncelle");
        albumGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumGuncelleActionPerformed(evt);
            }
        });
        getContentPane().add(albumGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, 80, 30));

        sanatciGuncelleButonu.setText("Sanatçı Güncelle");
        sanatciGuncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciGuncelleButonuActionPerformed(evt);
            }
        });
        getContentPane().add(sanatciGuncelleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, 30));

        sarkiSilButonu.setText("Şarkı Sil");
        sarkiSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkiSilButonuActionPerformed(evt);
            }
        });
        getContentPane().add(sarkiSilButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 110, 30));

        albumSilButonu.setText("Albüm Sil");
        albumSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumSilButonuActionPerformed(evt);
            }
        });
        getContentPane().add(albumSilButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 90, 30));

        sanatciSilButonu.setText("Sanatçı Sil");
        sanatciSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciSilButonuActionPerformed(evt);
            }
        });
        getContentPane().add(sanatciSilButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 30));

        albumTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Albüm", "Sanatçı", "Şarkı", "Tarih", "Tur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        albumTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(albumTablosu);
        if (albumTablosu.getColumnModel().getColumnCount() > 0) {
            albumTablosu.getColumnModel().getColumn(0).setResizable(false);
            albumTablosu.getColumnModel().getColumn(1).setResizable(false);
            albumTablosu.getColumnModel().getColumn(2).setResizable(false);
            albumTablosu.getColumnModel().getColumn(3).setResizable(false);
            albumTablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 395, 183));

        sarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı", "Tarih", "Sanatçı", "Albüm", "Tür", "Süre", "Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(sarkiTablosu);
        if (sarkiTablosu.getColumnModel().getColumnCount() > 0) {
            sarkiTablosu.getColumnModel().getColumn(0).setResizable(false);
            sarkiTablosu.getColumnModel().getColumn(1).setResizable(false);
            sarkiTablosu.getColumnModel().getColumn(2).setResizable(false);
            sarkiTablosu.getColumnModel().getColumn(3).setResizable(false);
            sarkiTablosu.getColumnModel().getColumn(4).setResizable(false);
            sarkiTablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 450, 183));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        jTextField1.setText("Şarkı Tablosu");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 0, 51));
        jTextField2.setText("ALBÜM TABLOSU");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 120, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 51, 0));
        jTextField3.setText("SANATÇI TABLOSU");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 120, -1));

        jTextField10.setText("Albüm :");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 110, -1));

        jTextField11.setText("Sanatçı :");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 110, -1));

        jTextField12.setText("Şarkı :");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 110, -1));

        jTextField13.setText("Dinlenme Sayısı :");
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 110, -1));

        jTextField14.setText("Tür   :");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 110, -1));

        jTextField15.setText("Tarih :");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 110, -1));

        sarkiAdiAlani.setText(" ");
        getContentPane().add(sarkiAdiAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 100, -1));

        tarihAlani.setText(" ");
        getContentPane().add(tarihAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 100, -1));

        sanatciAlani.setText(" ");
        getContentPane().add(sanatciAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 100, -1));

        turAlani.setText(" ");
        getContentPane().add(turAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 100, -1));

        dinlenmeSayisiAlani.setText(" ");
        getContentPane().add(dinlenmeSayisiAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 100, -1));

        albumAlani.setText(" ");
        getContentPane().add(albumAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 100, -1));

        jTextField16.setText("Ülke  :");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 110, -1));

        ulkeAlani.setText(" ");
        getContentPane().add(ulkeAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 100, -1));

        jTextField17.setText("sure  :");
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 110, -1));

        sureAlani.setText(" ");
        getContentPane().add(sureAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 100, -1));

        yenileButonu.setText("YENİLE");
        yenileButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButonuActionPerformed(evt);
            }
        });
        getContentPane().add(yenileButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanatciSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciSilButonuActionPerformed
     kullaniciIslemleri.sanatciSil(sanatciAlani.getText());
    }//GEN-LAST:event_sanatciSilButonuActionPerformed

    private void sanatciEkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciEkleButonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sanatciEkleButonuActionPerformed

    private void sanatciTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanatciTablosuMouseClicked
        sarkiAdiAlani.setText("");
        tarihAlani.setText("");
        sanatciAlani.setText("");
        albumAlani.setText("");
        turAlani.setText("");
        sureAlani.setText("");
        dinlenmeSayisiAlani.setText("");
        ulkeAlani.setText("");
        int selectedRow = sanatciTablosu.getSelectedRow();

        sanatciAlani.setText(sanatciModel.getValueAt(selectedRow, 0).toString());
        ulkeAlani.setText(sanatciModel.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_sanatciTablosuMouseClicked

    private void sarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sarkiTablosuMouseClicked

        sarkiAdiAlani.setText("");
        tarihAlani.setText("");
        sanatciAlani.setText("");
        albumAlani.setText("");
        turAlani.setText("");
        sureAlani.setText("");
        dinlenmeSayisiAlani.setText("");
        ulkeAlani.setText("");
        int selectedRow = sarkiTablosu.getSelectedRow();

        sarkiAdiAlani.setText(sarkiModel.getValueAt(selectedRow, 0).toString());
        tarihAlani.setText(sarkiModel.getValueAt(selectedRow, 1).toString());
        sanatciAlani.setText(sarkiModel.getValueAt(selectedRow, 2).toString());
        albumAlani.setText(sarkiModel.getValueAt(selectedRow, 3).toString());
        turAlani.setText(sarkiModel.getValueAt(selectedRow, 4).toString());
        sureAlani.setText(sarkiModel.getValueAt(selectedRow, 5).toString());
        dinlenmeSayisiAlani.setText(sarkiModel.getValueAt(selectedRow, 6).toString());


    }//GEN-LAST:event_sarkiTablosuMouseClicked

    private void albumTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumTablosuMouseClicked
        sarkiAdiAlani.setText("");
        tarihAlani.setText("");
        sanatciAlani.setText("");
        albumAlani.setText("");
        turAlani.setText("");
        sureAlani.setText("");
        dinlenmeSayisiAlani.setText("");
        ulkeAlani.setText("");
        int selectedRow = albumTablosu.getSelectedRow();
        albumAlani.setText(albumModel.getValueAt(selectedRow,0).toString());
        sanatciAlani.setText(albumModel.getValueAt(selectedRow, 1).toString());
        sarkiAdiAlani.setText(albumModel.getValueAt(selectedRow, 2).toString());
        tarihAlani.setText(albumModel.getValueAt(selectedRow, 3).toString());

        turAlani.setText(albumModel.getValueAt(selectedRow, 4).toString());

    }//GEN-LAST:event_albumTablosuMouseClicked

    private void yenileButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButonuActionPerformed
        sanatciTablosunuGoruntule();
        sarkiTablosunuGoruntule();
        albumTablosunuGoruntule();
    }//GEN-LAST:event_yenileButonuActionPerformed

    private void albumSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumSilButonuActionPerformed
        kullaniciIslemleri.albumSil(albumAlani.getText());
    }//GEN-LAST:event_albumSilButonuActionPerformed

    private void sarkiSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkiSilButonuActionPerformed
        kullaniciIslemleri.sarkiSil(sarkiAdiAlani.getText());
    }//GEN-LAST:event_sarkiSilButonuActionPerformed

    private void sanatciGuncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciGuncelleButonuActionPerformed
    int selectedrow = sanatciTablosu.getSelectedRow();
        kullaniciIslemleri.sanatciGuncelle(sanatciAlani.getText(), sanatciModel.getValueAt(selectedrow, 0).toString(), ulkeAlani.getText(),sanatciModel.getValueAt(selectedrow, 1).toString());
        
    }//GEN-LAST:event_sanatciGuncelleButonuActionPerformed

    private void albumGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumGuncelleActionPerformed
      int selectedrow = albumTablosu.getSelectedRow();
      kullaniciIslemleri.albumGuncelle(albumAlani.getText(), albumModel.getValueAt(selectedrow, 0).toString(), sanatciAlani.getText(), albumModel.getValueAt(selectedrow, 1).toString(), tarihAlani.getText(), albumModel.getValueAt(selectedrow, 2).toString(), turAlani.getText(), albumModel.getValueAt(selectedrow, 3).toString());
    }//GEN-LAST:event_albumGuncelleActionPerformed

    
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField albumAlani;
    private javax.swing.JButton albumGuncelle;
    private javax.swing.JButton albumSilButonu;
    private javax.swing.JTable albumTablosu;
    private javax.swing.JTextField dinlenmeSayisiAlani;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField sanatciAlani;
    private javax.swing.JButton sanatciEkleButonu;
    private javax.swing.JButton sanatciGuncelleButonu;
    private javax.swing.JButton sanatciSilButonu;
    private javax.swing.JTable sanatciTablosu;
    private javax.swing.JTextField sarkiAdiAlani;
    private javax.swing.JButton sarkiGuncelle;
    private javax.swing.JButton sarkiSilButonu;
    private javax.swing.JTable sarkiTablosu;
    private javax.swing.JTextField sureAlani;
    private javax.swing.JTextField tarihAlani;
    private javax.swing.JTextField turAlani;
    private javax.swing.JTextField ulkeAlani;
    private javax.swing.JButton yenileButonu;
    // End of variables declaration//GEN-END:variables

    private void sanatciTablosunuGoruntule() {
        sanatciModel.setRowCount(0);
        ArrayList<SanatciBilgileri> sanatcilar = new ArrayList<SanatciBilgileri>();
        sanatcilar = sarkiIslemleri.sanatcilariGetir();
        if (sanatcilar != null) {
            for (SanatciBilgileri sanatci : sanatcilar) {
                Object[] eklenecek = {sanatci.getSanatciAd(), sanatci.getUlke()};
                sanatciModel.addRow(eklenecek);

            }

        }
    }

    private void sarkiTablosunuGoruntule() {
        sarkiModel.setRowCount(0);

        ArrayList<AdminIcinSarkiBilgileri> sarkilar = new ArrayList<AdminIcinSarkiBilgileri>();
        sarkilar = sarkiIslemleri.adminIcınSarkilariGetir();
        if (sarkilar != null) {
            for (AdminIcinSarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getTarih(), sarki.getSanatci(), sarki.getAlbum(), sarki.getTur(), sarki.getSure(), sarki.getDinlenmeSayisi()};
                sarkiModel.addRow(eklenecek);

            }

        }
    }

    private void albumTablosunuGoruntule() {
        albumModel.setRowCount(0);

        ArrayList<AdminIcinSarkiBilgileri> albumler = new ArrayList<AdminIcinSarkiBilgileri>();
        albumler = sarkiIslemleri.albumleriGetir();
        if (albumler != null) {
            for (AdminIcinSarkiBilgileri album : albumler) {
                Object[] eklenecek = {album.getAlbum(),album.getSanatci(),album.getSarkiAd(), album.getTarih(),  album.getTur()};
                albumModel.addRow(eklenecek);

            }

        }
    }
}
