/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro.lab.pkg2.pkg3;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class KullaniciAnaEkrani extends javax.swing.JFrame {

    KullaniciIslemleri kullaniciIslemleri = new KullaniciIslemleri();
    Islemler islemler = new Islemler();
    DefaultTableModel abdModel;
    DefaultTableModel trModel;
    DefaultTableModel italyaModel;
    DefaultTableModel ispanyaModel;
    DefaultTableModel popModel;
    DefaultTableModel jazzModel;
    DefaultTableModel klasikModel;
    DefaultTableModel genelModel;
    DefaultTableModel kullaniciPopModel;
    DefaultTableModel kullaniciJazzModel;
    DefaultTableModel kullaniciKlasikModel;

    SarkiIslemleri sarkiIslemleri = new SarkiIslemleri();
    String kullaniciAdi;
    String sifre;

    public KullaniciAnaEkrani() {

        initComponents();

        abdModel = (DefaultTableModel) abdTablo.getModel();
        trModel = (DefaultTableModel) trTablo.getModel();
        italyaModel = (DefaultTableModel) italyaTablo.getModel();
        ispanyaModel = (DefaultTableModel) ispanyaTablo.getModel();
        popModel = (DefaultTableModel) popTablo.getModel();
        jazzModel = (DefaultTableModel) jazzTablo.getModel();
        klasikModel = (DefaultTableModel) klasikTablo.getModel();
        kullaniciKlasikModel = (DefaultTableModel) kullaniciKlasikTablo.getModel();
        kullaniciPopModel = (DefaultTableModel) kullaniciPopTablo.getModel();
        kullaniciJazzModel = (DefaultTableModel) kullaniciJazzTablo.getModel();

        panel1.setVisible(false);
        panel2.setVisible(false);
        yenileButonu.setVisible(false);
        secilenSarkiPaneli.setVisible(false);
        genelModel = (DefaultTableModel) genelTablo.getModel();
        kullaniciGoruntuleButonu2.setVisible(false);
        sarkiEkleButonu.setVisible(false);
        top10Goruntule();
        kullanicininTablolariPaneli.setVisible(false);
        dinlemeButonu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*
    select sarki.sarkiAd,sanatci.sanatciAd,album.albumAd,tur.turAd,sarki.dinlenmeSayisi 
    from sarki,sanatci,album,tur where sarki.albumId=album.albumId and sarki.sanatciId=sanatci.sanatciId and sarki.turId=tur.turId 
    ORDER by sarki.dinlenmeSayisi desc
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        girisYapButonu = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        trTablo = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        abdTablo = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        italyaTablo = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        ispanyaTablo = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jazzTablo = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        klasikTablo = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane18 = new javax.swing.JScrollPane();
        genelTablo = new javax.swing.JTable();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane21 = new javax.swing.JScrollPane();
        popTablo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        kullaniciGoruntuleButonu2 = new javax.swing.JButton();
        secilenSarkiPaneli = new javax.swing.JPanel();
        sarkiAdiAlani = new javax.swing.JTextField();
        kutu3 = new javax.swing.JTextField();
        kutu4 = new javax.swing.JTextField();
        turAlani = new javax.swing.JTextField();
        kutu5 = new javax.swing.JTextField();
        kutu6 = new javax.swing.JTextField();
        sanatciAlani = new javax.swing.JTextField();
        albumAlani = new javax.swing.JTextField();
        kullanicininTablolariPaneli = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        kullaniciJazzTablo = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        kullaniciKlasikTablo = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        kullaniciPopTablo = new javax.swing.JTable();
        kutu1 = new javax.swing.JTextField();
        kutu2 = new javax.swing.JTextField();
        girisYapButonu2 = new javax.swing.JButton();
        kullaniciAdiAlani = new javax.swing.JTextField();
        sifreAlani = new javax.swing.JTextField();
        dinlemeButonu = new javax.swing.JButton();
        yenileButonu = new javax.swing.JButton();
        sarkiEkleButonu = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        girisYapButonu.setText("Giriş Yap");
        girisYapButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisYapButonuActionPerformed(evt);
            }
        });

        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trTabloMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(trTablo);
        if (trTablo.getColumnModel().getColumnCount() > 0) {
            trTablo.getColumnModel().getColumn(0).setResizable(false);
            trTablo.getColumnModel().getColumn(1).setResizable(false);
            trTablo.getColumnModel().getColumn(2).setResizable(false);
            trTablo.getColumnModel().getColumn(3).setResizable(false);
            trTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        abdTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        abdTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abdTabloMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(abdTablo);
        if (abdTablo.getColumnModel().getColumnCount() > 0) {
            abdTablo.getColumnModel().getColumn(0).setResizable(false);
            abdTablo.getColumnModel().getColumn(1).setResizable(false);
            abdTablo.getColumnModel().getColumn(2).setResizable(false);
            abdTablo.getColumnModel().getColumn(3).setResizable(false);
            abdTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        italyaTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        italyaTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                italyaTabloMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(italyaTablo);
        if (italyaTablo.getColumnModel().getColumnCount() > 0) {
            italyaTablo.getColumnModel().getColumn(0).setResizable(false);
            italyaTablo.getColumnModel().getColumn(1).setResizable(false);
            italyaTablo.getColumnModel().getColumn(2).setResizable(false);
            italyaTablo.getColumnModel().getColumn(3).setResizable(false);
            italyaTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField7.setText("İTALYA TOP 10");
        jTextField7.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField5.setText("TR Top 10");
        jTextField5.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField4.setText("ABD Top 10");
        jTextField4.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        ispanyaTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ispanyaTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ispanyaTabloMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(ispanyaTablo);
        if (ispanyaTablo.getColumnModel().getColumnCount() > 0) {
            ispanyaTablo.getColumnModel().getColumn(0).setResizable(false);
            ispanyaTablo.getColumnModel().getColumn(1).setResizable(false);
            ispanyaTablo.getColumnModel().getColumn(2).setResizable(false);
            ispanyaTablo.getColumnModel().getColumn(3).setResizable(false);
            ispanyaTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField6.setText("İSPANYA Top 10");
        jTextField6.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 220));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1058, 6, -1, -1));

        jazzTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jazzTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jazzTabloMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(jazzTablo);
        if (jazzTablo.getColumnModel().getColumnCount() > 0) {
            jazzTablo.getColumnModel().getColumn(0).setResizable(false);
            jazzTablo.getColumnModel().getColumn(1).setResizable(false);
            jazzTablo.getColumnModel().getColumn(2).setResizable(false);
            jazzTablo.getColumnModel().getColumn(3).setResizable(false);
            jazzTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        klasikTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        klasikTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klasikTabloMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(klasikTablo);
        if (klasikTablo.getColumnModel().getColumnCount() > 0) {
            klasikTablo.getColumnModel().getColumn(0).setResizable(false);
            klasikTablo.getColumnModel().getColumn(1).setResizable(false);
            klasikTablo.getColumnModel().getColumn(2).setResizable(false);
            klasikTablo.getColumnModel().getColumn(3).setResizable(false);
            klasikTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField10.setText("JAZZ Top 10");
        jTextField10.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField11.setText("POP TOP 10");
        jTextField11.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        genelTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        genelTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genelTabloMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(genelTablo);
        if (genelTablo.getColumnModel().getColumnCount() > 0) {
            genelTablo.getColumnModel().getColumn(0).setResizable(false);
            genelTablo.getColumnModel().getColumn(1).setResizable(false);
            genelTablo.getColumnModel().getColumn(2).setResizable(false);
            genelTablo.getColumnModel().getColumn(3).setResizable(false);
            genelTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField12.setText("GENEL Top 10");
        jTextField12.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField13.setText("KLASİK TOP 10");
        jTextField13.setCaretColor(new java.awt.Color(51, 51, 255));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        popTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        popTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popTabloMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(popTablo);
        if (popTablo.getColumnModel().getColumnCount() > 0) {
            popTablo.getColumnModel().getColumn(0).setResizable(false);
            popTablo.getColumnModel().getColumn(1).setResizable(false);
            popTablo.getColumnModel().getColumn(2).setResizable(false);
            popTablo.getColumnModel().getColumn(3).setResizable(false);
            popTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1370, 260));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kullaniciGoruntuleButonu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        kullaniciGoruntuleButonu2.setText("Kullanıcıları Görüntüle");
        kullaniciGoruntuleButonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciGoruntuleButonu2ActionPerformed(evt);
            }
        });
        getContentPane().add(kullaniciGoruntuleButonu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 180, 52));

        sarkiAdiAlani.setEditable(false);
        sarkiAdiAlani.setText(" ");
        sarkiAdiAlani.setCaretColor(new java.awt.Color(51, 51, 255));
        sarkiAdiAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkiAdiAlaniActionPerformed(evt);
            }
        });

        kutu3.setEditable(false);
        kutu3.setText("Şarkı Adı :");

        kutu4.setEditable(false);
        kutu4.setText("Tür  :");

        turAlani.setEditable(false);
        turAlani.setText(" ");
        turAlani.setCaretColor(new java.awt.Color(51, 51, 255));
        turAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turAlaniActionPerformed(evt);
            }
        });

        kutu5.setEditable(false);
        kutu5.setText("Sanatçı  :");

        kutu6.setEditable(false);
        kutu6.setText("Album  :");

        sanatciAlani.setEditable(false);
        sanatciAlani.setText(" ");
        sanatciAlani.setCaretColor(new java.awt.Color(51, 51, 255));
        sanatciAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciAlaniActionPerformed(evt);
            }
        });

        albumAlani.setEditable(false);
        albumAlani.setText(" ");
        albumAlani.setCaretColor(new java.awt.Color(51, 51, 255));
        albumAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumAlaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secilenSarkiPaneliLayout = new javax.swing.GroupLayout(secilenSarkiPaneli);
        secilenSarkiPaneli.setLayout(secilenSarkiPaneliLayout);
        secilenSarkiPaneliLayout.setHorizontalGroup(
            secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kutu4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                .addGroup(secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(kutu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sarkiAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(kutu5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sanatciAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(kutu6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(albumAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        secilenSarkiPaneliLayout.setVerticalGroup(
            secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secilenSarkiPaneliLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sarkiAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kutu3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sanatciAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kutu5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kutu6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(secilenSarkiPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kutu4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(secilenSarkiPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 170));

        kullaniciJazzTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane22.setViewportView(kullaniciJazzTablo);
        if (kullaniciJazzTablo.getColumnModel().getColumnCount() > 0) {
            kullaniciJazzTablo.getColumnModel().getColumn(0).setResizable(false);
            kullaniciJazzTablo.getColumnModel().getColumn(1).setResizable(false);
            kullaniciJazzTablo.getColumnModel().getColumn(2).setResizable(false);
            kullaniciJazzTablo.getColumnModel().getColumn(3).setResizable(false);
            kullaniciJazzTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        kullaniciKlasikTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane23.setViewportView(kullaniciKlasikTablo);
        if (kullaniciKlasikTablo.getColumnModel().getColumnCount() > 0) {
            kullaniciKlasikTablo.getColumnModel().getColumn(0).setResizable(false);
            kullaniciKlasikTablo.getColumnModel().getColumn(1).setResizable(false);
            kullaniciKlasikTablo.getColumnModel().getColumn(2).setResizable(false);
            kullaniciKlasikTablo.getColumnModel().getColumn(3).setResizable(false);
            kullaniciKlasikTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        kullaniciPopTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı Adı", "Sanatçı", "Albüm", "Tur", "Dinlenme Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane20.setViewportView(kullaniciPopTablo);
        if (kullaniciPopTablo.getColumnModel().getColumnCount() > 0) {
            kullaniciPopTablo.getColumnModel().getColumn(0).setResizable(false);
            kullaniciPopTablo.getColumnModel().getColumn(1).setResizable(false);
            kullaniciPopTablo.getColumnModel().getColumn(2).setResizable(false);
            kullaniciPopTablo.getColumnModel().getColumn(3).setResizable(false);
            kullaniciPopTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout kullanicininTablolariPaneliLayout = new javax.swing.GroupLayout(kullanicininTablolariPaneli);
        kullanicininTablolariPaneli.setLayout(kullanicininTablolariPaneliLayout);
        kullanicininTablolariPaneliLayout.setHorizontalGroup(
            kullanicininTablolariPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullanicininTablolariPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kullanicininTablolariPaneliLayout.setVerticalGroup(
            kullanicininTablolariPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanicininTablolariPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullanicininTablolariPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kullanicininTablolariPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 850, 200));

        kutu1.setEditable(false);
        kutu1.setText("Kullanıcı Adı  :");
        getContentPane().add(kutu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 100, 42));

        kutu2.setEditable(false);
        kutu2.setText("Şifre :");
        kutu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutu2ActionPerformed(evt);
            }
        });
        getContentPane().add(kutu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 100, 40));

        girisYapButonu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        girisYapButonu2.setText("Giriş Yap");
        girisYapButonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisYapButonu2ActionPerformed(evt);
            }
        });
        getContentPane().add(girisYapButonu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 130, 30));

        kullaniciAdiAlani.setText(" ");
        getContentPane().add(kullaniciAdiAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 158, 42));

        sifreAlani.setText(" ");
        sifreAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreAlaniActionPerformed(evt);
            }
        });
        getContentPane().add(sifreAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 158, 40));

        dinlemeButonu.setText("Dinle");
        getContentPane().add(dinlemeButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 170, 40));

        yenileButonu.setText("YENİLE");
        yenileButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButonuActionPerformed(evt);
            }
        });
        getContentPane().add(yenileButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 90, -1));

        sarkiEkleButonu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        sarkiEkleButonu.setText("Şarkı Ekle");
        sarkiEkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkiEkleButonuActionPerformed(evt);
            }
        });
        getContentPane().add(sarkiEkleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 180, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void top10Goruntule() {
        abdModel.setRowCount(0);
        trModel.setRowCount(0);
        italyaModel.setRowCount(0);
        ispanyaModel.setRowCount(0);
        popModel.setRowCount(0);
        jazzModel.setRowCount(0);
        klasikModel.setRowCount(0);

        genelModel.setRowCount(0);

        ArrayList<SarkiBilgileri> sarkilar = new ArrayList<SarkiBilgileri>();

        sarkilar = sarkiIslemleri.genelTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                genelModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.abdTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                abdModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.italyaTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                italyaModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.ispanyaTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                ispanyaModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.popTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                popModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.jazzTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                jazzModel.addRow(eklenecek);

            }

        }
        sarkilar = sarkiIslemleri.klasikTabloSarkilariGetir();
        if (sarkilar != null) {
            for (SarkiBilgileri sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiAd(), sarki.getSanatciAd(), sarki.getAlbumAd(), sarki.getTur(), sarki.getDinlenmeSayisi()};
                klasikModel.addRow(eklenecek);

            }

        }
    }

    public void kullanicininKlasikListesiniGoruntule() {
        kullaniciKlasikModel.setRowCount(0);

        ArrayList<CalmaListeleriBilgileri> calmaListeleri = new ArrayList<CalmaListeleriBilgileri>();

        calmaListeleri = kullaniciIslemleri.klasikCalmaListesiniGetir(kullaniciAdiAlani.getText(), sifreAlani.getText());
        if (calmaListeleri != null) {
            for (CalmaListeleriBilgileri calmaListesi : calmaListeleri) {
                Object[] eklenecek = {calmaListesi.getSarkiAd(), calmaListesi.getSanatciAd(), calmaListesi.getAlbum(), calmaListesi.getDinlenmeSayisi(), calmaListesi.getTur()};
                kullaniciKlasikModel.addRow(eklenecek);

            }

        }
    }

    public void kullanicininJazzListesiniGoruntule() {
        kullaniciJazzModel.setRowCount(0);

        ArrayList<CalmaListeleriBilgileri> calmaListeleri = new ArrayList<CalmaListeleriBilgileri>();

        calmaListeleri = kullaniciIslemleri.jazzCalmaListesiniGetir(kullaniciAdiAlani.getText(), sifreAlani.getText());
        if (calmaListeleri != null) {
            for (CalmaListeleriBilgileri calmaListesi : calmaListeleri) {
                Object[] eklenecek = {calmaListesi.getSarkiAd(), calmaListesi.getSanatciAd(), calmaListesi.getAlbum(), calmaListesi.getDinlenmeSayisi(), calmaListesi.getTur()};
                kullaniciJazzModel.addRow(eklenecek);

            }

        }
    }

    public void kullanicininPopListesiniGoruntule() {
        kullaniciPopModel.setRowCount(0);

        ArrayList<CalmaListeleriBilgileri> calmaListeleri = new ArrayList<CalmaListeleriBilgileri>();

        calmaListeleri = kullaniciIslemleri.popCalmaListesiniGetir(kullaniciAdiAlani.getText(), sifreAlani.getText());
        if (calmaListeleri != null) {
            for (CalmaListeleriBilgileri calmaListesi : calmaListeleri) {
                Object[] eklenecek = {calmaListesi.getSarkiAd(), calmaListesi.getSanatciAd(), calmaListesi.getAlbum(), calmaListesi.getDinlenmeSayisi(), calmaListesi.getTur()};
                kullaniciPopModel.addRow(eklenecek);

            }

        }
    }

    private void girisYapButonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisYapButonu2ActionPerformed
        Islemler islemler = new Islemler();

        panel2.setVisible(true);

        kullaniciAdi = kullaniciAdiAlani.getText();
        sifre = sifreAlani.getText();
        String parola = sifreAlani.getText();

        boolean girisBasarili = islemler.girisYap(kullaniciAdi, parola);
        if (girisBasarili) {
            kullaniciAdiAlani.setVisible(false);
            sifreAlani.setVisible(false);
            kutu1.setVisible(false);
            kutu2.setVisible(false);
            kullaniciGoruntuleButonu2.setVisible(true);
            girisYapButonu2.setVisible(false);
            sarkiEkleButonu.setVisible(true);
            secilenSarkiPaneli.setVisible(true);
            panel1.setVisible(true);
            kullanicininTablolariPaneli.setVisible(true);
            kullanicininJazzListesiniGoruntule();
            kullanicininPopListesiniGoruntule();
            kullanicininKlasikListesiniGoruntule();
            yenileButonu.setVisible(true);
        } else {
            setVisible(false);

        }


    }//GEN-LAST:event_girisYapButonu2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void girisYapButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisYapButonuActionPerformed


    }//GEN-LAST:event_girisYapButonuActionPerformed

    private void turAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turAlaniActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void sarkiEkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkiEkleButonuActionPerformed

        String sarkiAdi = sarkiAdiAlani.getText();
        String sanatci = sanatciAlani.getText();
        String album = albumAlani.getText();
        String tur = turAlani.getText();

        int selectedRow = genelTablo.getSelectedRow();
        int selectedRow2 = jazzTablo.getSelectedRow();
        int selectedRow3 = klasikTablo.getSelectedRow();
        int selectedRow4 = popTablo.getSelectedRow();
        int selectedRow5 = ispanyaTablo.getSelectedRow();
        int selectedRow6 = italyaTablo.getSelectedRow();
        int selectedRow7 = trTablo.getSelectedRow();
        int selectedRow8 = abdTablo.getSelectedRow();

        if (selectedRow == -1 && selectedRow2 == -1 && selectedRow3 == -1 && selectedRow3 == -1 && selectedRow4 == -1 && selectedRow5 == -1 && selectedRow6 == -1 && selectedRow7 == -1 && selectedRow8 == -1) {
            if (genelModel.getRowCount() == 0) {
//                    mesajYazisi.setText("çalışanlar tablosu şuanda boş ");
            } else {
//                mesajYazisi.setText("lütfen güncellenecek bir çalışan seçin");
            }
        } else {
            System.out.println(kullaniciAdi + "," + sifre);
            islemler.kullaniciyaAnaSayfadanSarkiEkle(kullaniciAdi, sifre, sarkiAdi, sanatci, album, tur);

        }
    }//GEN-LAST:event_sarkiEkleButonuActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed

    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void kullaniciGoruntuleButonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciGoruntuleButonu2ActionPerformed
        setVisible(false);
        KullanicilarEkrani kullanicilarEkrani = new KullanicilarEkrani(kullaniciAdi, sifre);

        kullanicilarEkrani.setVisible(true);
    }//GEN-LAST:event_kullaniciGoruntuleButonu2ActionPerformed

    private void genelTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genelTabloMouseClicked
        int selectedRow = genelTablo.getSelectedRow();

        sarkiAdiAlani.setText(genelModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(genelModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(genelModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(genelModel.getValueAt(selectedRow, 3).toString());

    }//GEN-LAST:event_genelTabloMouseClicked

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void sarkiAdiAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkiAdiAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sarkiAdiAlaniActionPerformed

    private void sanatciAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sanatciAlaniActionPerformed

    private void albumAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumAlaniActionPerformed

    private void sifreAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreAlaniActionPerformed

    private void kutu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kutu2ActionPerformed

    private void jazzTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jazzTabloMouseClicked
        int selectedRow = jazzTablo.getSelectedRow();

        sarkiAdiAlani.setText(jazzModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(jazzModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(jazzModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(jazzModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_jazzTabloMouseClicked

    private void klasikTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_klasikTabloMouseClicked
        int selectedRow = klasikTablo.getSelectedRow();

        sarkiAdiAlani.setText(klasikModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(klasikModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(klasikModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(klasikModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_klasikTabloMouseClicked

    private void popTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popTabloMouseClicked
        int selectedRow = popTablo.getSelectedRow();

        sarkiAdiAlani.setText(popModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(popModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(popModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(popModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_popTabloMouseClicked

    private void trTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trTabloMouseClicked
        int selectedRow = trTablo.getSelectedRow();

        sarkiAdiAlani.setText(trModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(trModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(trModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(trModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_trTabloMouseClicked

    private void abdTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abdTabloMouseClicked
        int selectedRow = abdTablo.getSelectedRow();

        sarkiAdiAlani.setText(abdModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(abdModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(abdModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(abdModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_abdTabloMouseClicked

    private void italyaTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italyaTabloMouseClicked
        int selectedRow = italyaTablo.getSelectedRow();

        sarkiAdiAlani.setText(italyaModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(italyaModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(italyaModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(italyaModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_italyaTabloMouseClicked

    private void ispanyaTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ispanyaTabloMouseClicked
        int selectedRow = ispanyaTablo.getSelectedRow();

        sarkiAdiAlani.setText(ispanyaModel.getValueAt(selectedRow, 0).toString());
        sanatciAlani.setText(ispanyaModel.getValueAt(selectedRow, 1).toString());
        albumAlani.setText(ispanyaModel.getValueAt(selectedRow, 2).toString());
        turAlani.setText(ispanyaModel.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_ispanyaTabloMouseClicked

    private void yenileButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButonuActionPerformed
        kullanicininJazzListesiniGoruntule();
        kullanicininPopListesiniGoruntule();
        kullanicininKlasikListesiniGoruntule();
    }//GEN-LAST:event_yenileButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciAnaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable abdTablo;
    private javax.swing.JTextField albumAlani;
    private javax.swing.JButton dinlemeButonu;
    private javax.swing.JTable genelTablo;
    private javax.swing.JButton girisYapButonu;
    private javax.swing.JButton girisYapButonu2;
    private javax.swing.JTable ispanyaTablo;
    private javax.swing.JTable italyaTablo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable jazzTablo;
    private javax.swing.JTable klasikTablo;
    private javax.swing.JTextField kullaniciAdiAlani;
    private javax.swing.JButton kullaniciGoruntuleButonu2;
    private javax.swing.JTable kullaniciJazzTablo;
    private javax.swing.JTable kullaniciKlasikTablo;
    private javax.swing.JTable kullaniciPopTablo;
    private javax.swing.JPanel kullanicininTablolariPaneli;
    private javax.swing.JTextField kutu1;
    private javax.swing.JTextField kutu2;
    private javax.swing.JTextField kutu3;
    private javax.swing.JTextField kutu4;
    private javax.swing.JTextField kutu5;
    private javax.swing.JTextField kutu6;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable popTablo;
    private javax.swing.JTextField sanatciAlani;
    private javax.swing.JTextField sarkiAdiAlani;
    private javax.swing.JButton sarkiEkleButonu;
    private javax.swing.JPanel secilenSarkiPaneli;
    private javax.swing.JTextField sifreAlani;
    private javax.swing.JTable trTablo;
    private javax.swing.JTextField turAlani;
    private javax.swing.JButton yenileButonu;
    // End of variables declaration//GEN-END:variables
}
